language: generic

sudo: required

services:
 - docker

before_install:
 - docker build -t plainds82/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
 - docker run -e CI=true plainds82/react-test-app npm run test

after_install:
 - docker build -t plainds82/docker-frontend  ./frontend
 - docker build -t plainds82/docker-backend   ./backend
 - docker build -t plainds82/docker-nginx     ./nginx

 - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

 - docker push plainds82/docker-frontend
 - docker push plainds82/docker-backend
 - docker push plainds82/docker-nginx